import express from "express";
import multer from "multer";
import { CloudinaryStorage } from "multer-storage-cloudinary";
import NavbarSettings from "../models/NavbarSettings.js";
// --- IMPORT YOUR EXISTING CONFIG HERE ---
import cloudinary from "../config/cloudinary.js";

const router = express.Router();

// 2. Setup the Storage using YOUR cloudinary instance
const storage = new CloudinaryStorage({
  cloudinary: cloudinary, // Use the imported instance
  params: {
    folder: "navbar_branding",
    allowed_formats: ["jpg", "png", "svg", "webp"],
    public_id: (req, file) => `logo-${Date.now()}`,
  },
});

const uploadLogo = multer({ storage: storage });

// 3. The Upload Route
router.post("/upload-logo", uploadLogo.single("logo"), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: "No file uploaded" });
    }

    // req.file.path is the URL generated by your cloudinary config
    const updated = await NavbarSettings.findOneAndUpdate(
      {},
      { logoImage: req.file.path },
      { new: true, upsert: true }
    );

    res.json({
      message: "Logo uploaded using existing Cloudinary config",
      logo: req.file.path,
      navbar: updated,
    });
  } catch (error) {
    console.error("Upload Error:", error);
    res.status(500).json({ error: "Server error during upload" });
  }
});

// Standard GET route for verification
router.get("/", async (req, res) => {
  const navbar = await NavbarSettings.findOne();
  res.json(navbar);
});

export default router;     